spring.application.name=Java-sprinboot

# ============================================
# PostgreSQL (Docker)
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/javasprinboot
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=openpg
spring.datasource.password=***

# Initialisation de la BDD (cr�e la table + seed admin au d�marrage)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Port serveur
server.port=8080
